config/routes.rb
# frozen_string_literal: true

Rails.application.routes.draw do
  root to: 'attendances#new'

  get '/signup', to: 'users#new'
  post '/users', to: 'users#create'

  get    '/signin',   to: 'sessions#new'
  post   '/signin',   to: 'sessions#create'
  delete '/signout',  to: 'sessions#destroy'

  get 'attendances/new', to: 'attendances#new'
  get 'attendances', to: 'attendances#index'

  post 'attendances/work_in', to: 'attendances_work_in#create'
  post 'attendances/break_in', to: 'attendances_break_in#create'
  post 'attendances/break_out', to: 'attendances_break_out#create'
  post 'attendances/work_out', to: 'attendances_work_out#create'

end

app/models/application_record.rb
# frozen_string_literal: true

class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/attendance.rb
# frozen_string_literal: true

class Attendance < ApplicationRecord
  validates :user_id, presence: true

  def restraint_time
    if work_out
      work_out - work_in
    else
      0
    end
  end

  def work_time
    if work_out
      work_out - work_in - break_time
    else
      0
    end
  end
end

app/models/user.rb
# frozen_string_literal: true

class User < ApplicationRecord
  before_save { self.email = email.downcase }
  validates :name, presence: true,
                   length: { maximum: 20 }
  EMAIL_REGULAR_EXPRESSION = /\A[\w+\-.]+@[a-z\d\-]+(\.[a-z\d\-]+)*\.[a-z]+\z/i
  validates :email, presence: true,
                    length: { maximum: 100 },
                    format: { with: EMAIL_REGULAR_EXPRESSION },
                    uniqueness: { case_sensitive: false }
  has_secure_password
  validates :password, presence: true, length: { minimum: 6 }

  has_many :attendances
end

app/controllers/application_controller.rb
# frozen_string_literal: true

class ApplicationController < ActionController::Base
  include SessionsHelper
  before_action :login_check
  def login_check
    return if signed_in?

    flash[:alert] = 'Please log in.'
    redirect_to signin_path
  end
end

app/controllers/attendances_break_in_controller.rb
class AttendancesBreakInController < AttendancesController
  def create
    return unless @record || !@record.work_in.nil?

    @record.break_in = current_date_time
    @record.save
    redirect_to attendances_new_path
  end
end

app/controllers/attendances_break_out_controller.rb
class AttendancesBreakOutController < AttendancesController
  def create
    return unless @record || (!@record.work_in.nil? && !@record.break_in.nil?)

    @record.break_out = current_date_time
    @record.break_time += @record.break_out - @record.break_in
    @record.save
    redirect_to attendances_new_path
  end
end

app/controllers/attendances_controller.rb
# frozen_string_literal: true

class AttendancesController < ApplicationController
  before_action :set_record
  require 'date'

  def index
    @wdays = %w[日 月 火 水 木 金 土]
    day = params[:year_month] ? Date.parse("#{params[:year_month][0]}-01") : Date.today
    @start_date = day.beginning_of_month
    @end_date = day.end_of_month
    @month = day.month
    @attendances = current_user.attendances.where(work_date: @start_date..@end_date).each_with_object({}) do |attendance, hash|
      hash[attendance.work_date] = attendance
    end
  end

  def new
  end

  private

  def current_date_time
    DateTime.now
  end

  def fetch_current_attendance
    current_attendance = current_user.attendances.where(updated_at: Date.today.all_day).first
    current_attendance = current_user.attendances.new if current_attendance.nil?
    current_attendance
  end

  def set_record
    @record = fetch_current_attendance
  end
end

app/controllers/attendances_work_in_controller.rb
class AttendancesWorkInController < AttendancesController
  def create
    new_record = current_user.attendances.build
    new_record.work_in = current_date_time
    new_record.work_date = Date.today
    if new_record.save
      redirect_to attendances_new_path
    else
      Rails.logger.debug 'error'
    end
  end
end

app/controllers/attendances_work_out_controller.rb
class AttendancesWorkOutController < AttendancesController
  def create
    return unless @record || !@record.work_in.nil?

    @record.work_out = current_date_time
    @record.save
    redirect_to attendances_new_path
  end
end

app/controllers/sessions_controller.rb
# frozen_string_literal: true

class SessionsController < ApplicationController
  skip_before_action :login_check, only: %i[new create]
  def new
  end

  def create
    @user = User.find_by(email: params[:email].downcase)
    if @user.authenticate(params[:password])
      sign_in @user
      redirect_to attendances_new_path
    else
      redirect_to signin_path, flash: { error: 'メールアドレスとパスワードが一致しません' }
    end
  end

  def destroy
    sign_out
    redirect_to signin_path
  end

  def action
    user_id = params[:id]
    posts = User.fetch_post(user_id)
    render posts
  end
end

app/controllers/users_controller.rb
# frozen_string_literal: true

class UsersController < ApplicationController
  skip_before_action :login_check
  def new
    @user = User.new
  end

  def create
    @user = User.new(user_params)
    if @user.save
      sign_in @user
      redirect_to attendances_new_path
    else
      redirect_to signup_path, flash: { error: @user.errors.full_messages }
    end
  end

  private

  def user_params
    params.require(:user).permit(:name, :email, :password,
                                 :password_confirmation)
  end
end

app/helpers/application_helper.rb
# frozen_string_literal: true

module ApplicationHelper
end

app/helpers/attendances_helper.rb
# frozen_string_literal: true

module AttendancesHelper
  def time_to_view_data(time)
    hour = (time / 3600).round
    minute = (time % 3600 / 60).round
    "#{format('%02d', hour)}:#{format('%02d', minute)}"
  end
end

app/helpers/sessions_helper.rb
# frozen_string_literal: true

module SessionsHelper
  def sign_in(user)
    session[:user_id] = user.id
  end

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id]
  end

  def signed_in?
    !current_user.nil?
  end

  def sign_out
    session.delete(:user_id)
    @current_user = nil
  end
end

app/helpers/users_helper.rb
# frozen_string_literal: true

module UsersHelper
end

app/views/attendances/index.html.erb
<%= stylesheet_link_tag "attendances", :media => "all" %>
<div class="container">
  <p>勤務表</p>
  <%= form_tag(attendances_path, method: :get) do %>
    <%= month_field :year_month,'',class:"year-month-field"%>
    <%= submit_tag "選択",class:"year-month-choice" %>
  <% end %>
    <h1><%= "#{@month}月の勤務表" %></h1>
    <table>
      <thead>
      <tr>
        <th>日付</th>
        <th>曜日</th>
        <th>出社時間</th>
        <th>退社時間</th>
        <th>拘束時間</th>
        <th>勤務時間</th>
        <th>休憩時間</th>
      </tr>
      </thead>

      <% (Date.parse(@start_date.to_s)..Date.parse(@end_date.to_s)).each do |date| %>
        <% attendance = @attendances[date] || ActiveDecorator::Decorator.instance.decorate(Attendance.new) %>
        <tr>
          <td><%= date.strftime("%m月%d日") %></td>
          <td><%= @wdays[date.wday] %></td>
          <td><%= attendance.work_in_view_data %> </td>
          <td><%= attendance.work_out_view_data %> </td>
          <td><%= attendance.restraint_time_view_data %> </td>
          <td><%= attendance.work_time_view_data %> </td>
          <td><%= attendance.break_time_view_data %> </td>
        </tr>
      <% end %>
      <tr>
        <th colspan="4"></th>
        <th>拘束時間</th>
        <th>労働時間</th>
        <th>休憩時間</th>
      </tr>
      <tr>
        <td colspan="4"></td>
        <td><%= MonthAttendanceCollection.new(@attendances).restraint_time %></td>
        <td><%= MonthAttendanceCollection.new(@attendances).work_time %></td>
        <td><%= MonthAttendanceCollection.new(@attendances).break_time %></td>
      </tr>

    </table>
</div>

app/views/attendances/new.html.erb
<%= stylesheet_link_tag "attendances", :media => "all" %>
<div class = "container">
  <h1>出退勤記録表</h1>
  <div id="current_date"></p>
  <p id="clock"></p>
    <div class = "buttons">
      <%= @record.work_in_button  %>
      <%= @record.break_in_button  %>
      <%= @record.break_out_button  %>
      <%= @record.work_out_button  %>
    </div>
</div>
<h2>現在状況：<b><%= @record.worker_status %></b></h2>

<%= link_to "勤務表確認", attendances_path %>
<%= javascript_include_tag 'attendance_new' %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>AttendanceApp</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag 'application', media: 'all', 'data-turbolinks-track': 'reload' %>
    <%= javascript_pack_tag 'application', 'data-turbolinks-track': 'reload' %>
  </head>

  <body>
    <%= yield %>
  </body>

</html>

app/views/users/new.html.erb
<%= stylesheet_link_tag "users", :media => "all" %>
<div class = "container">
  <h1>新規登録</h1>
  <% if flash[:error].present? %>
      <% flash[:error].each do |e| %>
        <p class = "error"><%= e %></p>
      <% end %>
    <% end %>
  <%= form_with model: @user do |f| %>
    <%= f.label :名前%>
    <%= f.text_field :name,placeholder:"名前" %>
    <%= f.label :メールアドレス%>
    <%= f.email_field :email,placeholder:"example@gmail.com" %>
    <%= f.label :パスワード%>
    <%= f.password_field :password %>
    <%= f.label :パスワード確認%>
    <%= f.password_field :password_confirmation %>
    <br>
    <%= f.submit "会員登録",class: 'submit'%>
  <% end %>
  <%= link_to "ログイン",signin_path %>
</div>